# config.yaml

model:
  # model name ["clip_base", "clip_large", "openclip", "longclip", "align", "blip2"]
  name: "clip_base"

  # checkpoint path for "longclip" model:
  checkpoint_path: "/path/to/checkpoint.pt"

paths:
  csv_path: "/path/to/data.csv" #Path to csv file containing image paths and captions
  image_folder: "/path/to/images" #Path to folder containing images
  faiss_save_dir: "/path/to/faiss_save_dir" #Path to save faiss index
  results_dir: "/path/to/results" #Path to save results

dataset:
  # dataset name ["roco", "sharegpt4v", "factify", "urban1k"]
  name: "dataset_name" #Name used while saving results

token_steps:
  start: 1 #Start token length
  stop: 200 #Stop token length
  step: 10 #Step size for token length
